services:
  gas-app-blue:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gas-app-blue
    ports:
      - "4000:3000"   # Blue on host 4000 → container 3000
    environment:
      - PORT=3000

  gas-app-green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gas-app-green
    ports:
      - "4001:3000"   # Green on host 4001 → container 3000
    environment:
      - PORT=3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../infra/monitoring/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

