name: Canary Release

on:
  workflow_dispatch:

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - name: Start Canary Deploy (10%)
        run: echo "Route 10% of traffic to canary..."

      - name: Monitoring window
        run: sleep 20

      - name: Increase to 50%
        run: echo "Route 50% of traffic to canary..."

      - name: Monitoring window
        run: sleep 20

      - name: Promote Canary to 100%
        run: echo "Route 100% of traffic to canary..."

